import React from "react";
import { Link } from "react-router-dom";
import "./style.css";
import Header from "../Componets/header";
import Footer from "../Componets/Footer";

export default function Fav(){
    return (
        <main>
            <Header />
            <div className="container favoritos">
                <h1 className="headers"><span>#</span>Lista de Favoritos</h1>
                <section className="row listar">
                    <ul className="col-6">
                        <li>
                            <img src={require("../img/one piece.jpg")} alt="one"/><br />
                        </li>
                        <li>
                            <div className="detalhes">
                                <strong>One Piece</strong>
                                <p>
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                </p>
                                <Link to="/detalhes" className="btn btn-primary">
                                    mais...
                                </Link>
                            </div>
                        </li>
                    </ul>
                    <ul className="col-6">
                        <li>
                            <img src={require("../img/one piece.jpg")} alt="one"/><br />
                        </li>
                        <li>
                            <div className="detalhes">
                                <strong>One Piece</strong>
                                <p>
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                </p>
                                <Link to="/detalhes" className="btn btn-primary">
                                    mais...
                                </Link>
                            </div>
                        </li>
                    </ul>
                    <ul className="col-6">
                        <li>
                            <img src={require("../img/one piece.jpg")} alt="one"/><br />
                        </li>
                        <li>
                            <div className="detalhes">
                                <strong>One Piece</strong>
                                <p>
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                </p>
                                <Link to="/detalhes" className="btn btn-primary">
                                    mais...
                                </Link>
                            </div>
                        </li>
                    </ul>
                    <ul className="col-6">
                        <li>
                            <img src={require("../img/one piece.jpg")} alt="one"/><br />
                        </li>
                        <li>
                            <div className="detalhes">
                                <strong>One Piece</strong>
                                <p>
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                    Novo Manga...
                                </p>
                                <Link to="/detalhes" className="btn btn-primary">
                                    mais...
                                </Link>
                            </div>
                        </li>
                    </ul>   
                </section>
            </div>
            <Footer />
        </main>
    )
}